news/urls.py
from django.urls import path
from .views import PostList, NewsDetail, SearchList, NewCreateView, PostUpdate, PostDelete, BaseRegisterView, \
   IndexView
from django.contrib.auth.views import LoginView, LogoutView
from .views import upgrade_me


urlpatterns = [
   path('', PostList.as_view(), name='post_list'),
   path('<int:pk>', NewsDetail.as_view(), name='post_detail'),
   path('search/', SearchList.as_view(), name='post_search'),
   path('create/', NewCreateView.as_view(), name='post_create'),
   path('<int:pk>/edit/', PostUpdate.as_view(), name='post_update'),
   path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
   path('article/create/', NewCreateView.as_view(), name='post_article_create'),
   path('article/<int:pk>/edit/', PostUpdate.as_view(), name='post_article_update'),
   path('article/<int:pk>/delete/', PostDelete.as_view(), name='post_article_delete'),
   path('index/', IndexView.as_view(template_name='index.html'), name='index'),
   path('login/', LoginView.as_view(template_name='login.html'), name='login'),
   path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
   path('signup/', BaseRegisterView.as_view(template_name='signup.html'), name='signup'),
   path('upgrade/', upgrade_me, name='upgrade')

]

news_portal/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('news.urls')),
    path('accounts/', include('allauth.urls')),

]


news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django import forms
from allauth.account.forms import SignupForm
from django.contrib.auth.models import Group


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def update_rating(self):
        posts_rating = Post.objects.filter(author=self).aggregate(Sum('rating'))
        comments_rating = Comment.objects.filter(user=self.user).aggregate(Sum('rating'))
        posts_comments_rating = Comment.objects.filter(post__author=self).aggregate(Sum('rating'))

        self.rating = posts_rating * 3 + comments_rating + posts_comments_rating
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)


class Post(models.Model):
    objects = None
    article = 'AR'
    news = 'NE'

    POSITIONS = [
        (article, 'Статья'),
        (news, 'Новость')
    ]

    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    field_choice = models.CharField(max_length=2, choices=POSITIONS, default=news)
    datetime = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    rating_art_new = models.IntegerField(default=0)
    many_to_many_relation = models.ManyToManyField(Category, through='PostCategory')

    def like(self):
        self.rating_art_new += 1
        self.save()

    def dislike(self):
        self.rating_art_new -= 1
        self.save()

    def preview(self):
        return self.content[0:124] + '...'

    def __str__(self):
        return f'{self.title} ({self.datetime})'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class PostCategory(models.Model):
    one_to_many_relation = models.ForeignKey(Post, on_delete=models.CASCADE)
    one_to_many_relation1 = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    objects = None
    comment_post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=1024)
    comment_datetime = models.DateTimeField(auto_now_add=True)
    comment_rating = models.IntegerField(default=0)

    def like(self):
        self.comment_rating += 1
        self.save()

    def dislike(self):
        self.comment_rating -= 1
        self.save()


class BaseRegisterForm(UserCreationForm):
    email = forms.EmailField(label='Email')
    first_name = forms.CharField(label='Имя')
    last_name = forms.CharField(label='Фамилия')

    class Meta:
        model = User
        fields = ('username',
                  'first_name',
                  'last_name',
                  'email',
                  'password1',
                  'password2',)


class CommonSignupForm(SignupForm):

    def save(self, request):
        user = super(CommonSignupForm, self).save(request)
        basic_group = Group.objects.get(name='common')
        basic_group.user_set.add(user)
        return user

news/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Post
from django.contrib.auth.forms import AuthenticationForm


class PostForm(forms.ModelForm):
    content = forms.CharField(min_length=20)

    class Meta:
        model = Post
        fields = [
            'author',
            'title',
            'content',
            'many_to_many_relation',
        ]

    def clean(self):
        cleaned_data = super().clean()
        content = cleaned_data.get("content")
        if content is not None and len(content) < 20:
            raise ValidationError({
                "content": "Описание не может быть менее 20 символов."
            })

        title = cleaned_data.get("title")
        if title == content:
            raise ValidationError(
                "Описание не должно быть идентичным названию."
            )
        return cleaned_data


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields['username'].widget.attrs['placeholder'] = 'Логин пользователя'
            self.fields['password'].widget.attrs['placeholder'] = 'Пароль пользователя'
            self.fields['username'].label = 'Логин'
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })




news/views.py

from datetime import datetime
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from .models import Post, BaseRegisterForm
from .filters import PostFilter
from .forms import PostForm, UserLoginForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.auth.models import User
from flask import url_for
from django.shortcuts import redirect
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required


class PostList(ListView):
    model = Post
    ordering = '-datetime'
    template_name = 'news.html'
    context_object_name = 'news'
    paginate_by = 10  # количество записей на странице

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time'] = datetime.utcnow()
        context['next_sale'] = None
        context['filterset'] = self.filterset
        return context


class NewsDetail(DetailView):
    model = Post
    template_name = 'new.html'
    context_object_name = 'new'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time'] = datetime.utcnow()
        context['next_sale'] = None
        return context


class SearchList(ListView):
    model = Post
    template_name = 'search.html'
    context_object_name = 'search'
    filterset_class = PostFilter
    # paginate_by = 2

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


class NewCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = ('news.add_post',)
    model = Post
    template_name = 'create.html'
    context_object_name = 'create'
    form_class = PostForm

    def form_valid(self, form):
        post = form.save(commit=False)
        if self.request.path == '/news/article/create/':
            post.field_choice = 'AR'
        post.save()
        return super().form_valid(form)


class PostUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = ('news.change_post',)
    form_class = PostForm
    model = Post
    template_name = 'edit.html'
    context_object_name = 'edit'

    def form_valid(self, form):
        post = form.save(commit=False)
        if self.request.path == '/news/article/<int:pk>/edit/':
            post.update = 'AR'
        else:
            "Здесь редактируются только статьи."
        post.save()
        return super().form_valid(form)


class PostDelete(DeleteView):
    model = Post
    template_name = 'delete.html'
    success_url = reverse_lazy('post_list')
    context_object_name = 'delete'

    def form_valid(self, form):
        post = form.save(commit=False)
        if self.request.path == '/news/article/<int:pk>/delete/':
            post.field_choice = 'AR'
        post.save()
        return super().form_valid(form)


class PostUserUpdate(LoginRequiredMixin, LoginView):
    template_name = 'login.html'
    form_class = UserLoginForm
    context_object_name = 'login'
    success_message = 'Добро пожаловать на сайт!'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Авторизация на сайте'
        return context

    def current_view(self, request):
        current_user = request.user
        if current_user.is_authenticated:
            return redirect(url_for('news/'))
        else:
            return redirect(url_for('accounts/login/'))


class BaseRegisterView(CreateView):
    model = User
    form_class = BaseRegisterForm
    success_url = '/accounts/login/'
    template_name = 'signup.html'


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_authors'] = not self.request.user.groups.filter(name='authors').exists()
        return context


@login_required
def upgrade_me(request):
    user = request.user
    authors_group = Group.objects.get(name='authors')
    if not request.user.groups.filter(name='authors').exists():
        authors_group.user_set.add(user)
    return redirect('/')





templates/create.html
{% extends 'flatpages/default.html' %}


{% block content %}
<h1>Новость/статья</h1>

<br><form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить" />
</form>

{% endblock content %}

templates/delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление новости/статьи</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"?</p>
    <input type="submit" value="Удалить" />
</form>
{% endblock content %}

templates/edit.html
{% extends 'flatpages/default.html' %}


{% block content %}
<h1>Новость/статья</h1>

<br><form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Изменить" />
</form>

{% endblock content %}

templates/index.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h2>Страница авторизованного пользователя {{request.user.username}}</h2>
<div> Здесь может содержаться персональная информация для каждого пользователя </div>

<button> <a href="/accounts/logout/">Выйти</a> </button>

{% if is_not_authors %}
<button> <a href="/news/"> Хочу быть автором!</a> </button>
{% endif %}
{% endblock %}

templates/login.html
{% extends 'flatpages/default.html' %}


{% block content %}
<h2> Войти в систему </h2>
<form method="post" action="{% url 'login' %}">
{% csrf_token %}
    <div class="">
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table></div>

<input type="submit" value="Войти">
</form><br>
<button> <a href="/account/singup/"> Регистрация </a></button>
{% endblock %}

templates/logout.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h2> Вы вышли из системы </h2>
{% endblock %}

templates/new.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
{{ new.title }}
{% endblock title %}

{% block content %}
<h1>Новость</h1>

<h3 style="text-transform:uppercase">{{ new.title }}</h3>
    {{ new.content|censor }} <br>
    <h5>{{ new.datetime|date:'d M Y' }}</h5>

{% endblock content %}

templates/news.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
News
{% endblock title %}

{% block content %}
<h1>Общее количество новостей - {{news|length}}</h1>



{% for new in news %}
    <h4 style="text-transform:uppercase">{{ new.title }}</h4>
    ({{ new.datetime|date:'d M Y' }})
    -- {{ new.content|truncatechars:21 }} --
    {{ new.get_field_choice_display }}

{% endfor %}

{% for new in page_obj %}
    {{ new.full_name|upper }}<br>
    ...
{% endfor %}

{% if page_obj.has_previous %}
    <a href="?page=1">&laquo; Первая </a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
{% endif %}

Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}

{% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
           ...
            <a href="?page={{ page_obj.paginator.num_pages }}"> Последняя  &raquo;</a>
        {% endif %}
{% endif %}



{% endblock content %}

templates/search.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Search
{% endblock title %}

{% block content %}
<br><form action="" method="get">
    {{ filterset.form.as_p }}
    <input type="submit" value="Найти" />
</form>

{% if search %}
{% for news in search %}
    <h4 style="text-transform:uppercase">{{ new.title }}</h4>
    ({{ news.datetime|date:'d M Y' }})
    -- {{ news.content|truncatechars:21 }} --
    {{ news.author }}
{% endfor %}

{% else %}
    <br><h4>По указанным параметрам новостей нет!</h4>
{% endif %}



{% endblock content %}

templates/signup.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h2> Регистрация </h2>
<form method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Продолжить">
</form>
{% endblock %}